### ISSUE TITLE
Crash on RebuildCategrization

### ISSUE THREAD

**Issue by Xeroxxx** [ServUO/ServUO#2927]
https://github.com/ServUO/ServUO/blob/151e31a9af5e41050cfdd883b1237379ba65474e/Scripts/Services/TreasuresOfKotlCity/Items/PowerCoreDockingStations.cs#L10

**Comment by Xeroxxx** [comment]
Server Crash Report
===================

ServUO Version 0.5, Build 6582.22496
Operating System: Microsoft Windows NT 6.2.9200.0
.NET Framework: 4.0.30319.42000
Time: 08.01.2018 11:39:09
Mobiles: 2245
Items: 19833
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Server.Engines.TreasuresOfKotlCity.PowerCoreDockingStation.Delete()
   at Server.Items.AddonComponent.OnAfterDelete()
   at Server.Item.Delete() in c:\Users\XXX\Documents\GitHub\ServUO\Server\Item.cs:line 4356
   at Server.Items.BaseAddon.OnAfterDelete()
   at Server.Item.Delete() in c:\Users\XXX\Documents\GitHub\ServUO\Server\Item.cs:line 4356
   at Server.Engines.TreasuresOfKotlCity.PowerCoreDockingStation.Delete()
   at Server.Commands.Categorization.RecurseExport(XmlTextWriter xml, CategoryEntry ce)
   at Server.Commands.Categorization.RecurseExport(XmlTextWriter xml, CategoryEntry ce)
   at Server.Commands.Categorization.RecurseExport(XmlTextWriter xml, CategoryEntry ce)
   at Server.Commands.Categorization.RecurseExport(XmlTextWriter xml, CategoryEntry ce)
   at Server.Commands.Categorization.RecurseExport(XmlTextWriter xml, CategoryEntry ce)
   at Server.Commands.Categorization.Export(CategoryEntry ce, String fileName, String title)
   at Server.Commands.Categorization.RebuildCategorization_OnCommand(CommandEventArgs e)
   at Server.Commands.CommandSystem.Handle(Mobile from, String text, MessageType type) in c:\Users\XXX\Documents\GitHub\ServUO\Server\Commands.cs:line 264
   at Server.Gumps.AdminGump.InvokeCommand(String c)
   at Server.Gumps.AdminGump.OnResponse(NetState sender, RelayInfo info)
   at Server.Network.PacketHandlers.DisplayGumpResponse(NetState state, PacketReader pvSrc) in c:\Users\XXX\Documents\GitHub\ServUO\Server\Network\PacketHandlers.cs:line 1458
   at Server.Network.MessagePump.HandleReceive(NetState ns) in c:\Users\XXX\Documents\GitHub\ServUO\Server\Network\MessagePump.cs:line 187
   at Server.Network.MessagePump.Slice() in c:\Users\XXX\Documents\GitHub\ServUO\Server\Network\MessagePump.cs:line 121
   at Server.Core.Main(String[] args) in c:\Users\XXX\Documents\GitHub\ServUO\Server\Main.cs:line 588

Clients:
- Count: 1
+ 127.0.0.1: (account = XeroX) (mobile = 0x3B6 'XeroX')

**Comment by Xeroxxx** [comment]
@kevin-10 please look into this.
