### ISSUE TITLE
ConvertPlayers is broken

### ISSUE THREAD

**Issue by ggobbe** [ServUO/ServUO#4144]
The .convertPlayers command is broken. If there are mobiles that are players. 

To reproduce: 
1) Create a new type CustomPlayerMobile that inherits PlayerMobile
2) Add an empty constructor, one from a serial, then a Serialize and a Deserialize method that both calls to the base method then write and read their version
3) In the ConvertPlayers command, change the type PlayerMobile by CustomPlayerMobile
4) If you have players with clothes and/or jewels, it will crash when the command is ran.

**Reason**: 
There are various:
- Some properties are not initialized when copying the objets (e.g. m_Quests, Skills and other props). This results in NullReferenceExceptions. An easy fix is to copy the items after having copied the props and skills. There are still some private backing fields that lacks initialization (e.g. m_Quests).
- After than, when serializing the newly create CustomPlayerMobile, other properties such as Lists, are not initialized and will make the Write(List<Mobile>) throw a NullReferenceException.

**Example Stacktrace 1**
```System.NullReferenceException: Object reference not set to an instance of an object.
   at Server.Engines.Quests.QuestHelper.EnhancedSkill(PlayerMobile player, Skill skill)
   at Server.Misc.SkillCheck.Gain(Mobile from, Skill skill)
   at Server.Misc.SkillCheck.CheckSkill(Mobile from, Skill skill, Object amObj, Double chance)
   at Server.Misc.SkillCheck.Mobile_SkillCheckDirectLocation(Mobile from, SkillName skillName, Double chance)
   at Server.Mobiles.XmlSpawnerSkillCheck.Mobile_SkillCheckDirectLocation(Mobile from, SkillName skillName, Double chance)
   at Server.Misc.RegenRates.Mobile_StamRegenRate(Mobile from)
   at Server.Mobile.StamTimer..ctor(Mobile m) in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 2009
   at Server.Mobile.CheckStatTimers() in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 6345
   at Server.Items.BaseClothing.OnAdded(Object parent)
   at Server.Mobile.AddItem(Item item) in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 6867
   at Server.Commands.ConvertPlayers.Convert_OnCommand(CommandEventArgs e)
   at Server.Commands.CommandSystem.Handle(Mobile from, String text, MessageType type) in C:\Workspaces\src\uo\aube-uo\Server\Commands.cs:line 258
   at Server.Mobile.DoSpeech(String text, Int32[] keywords, MessageType type, Int32 hue) in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 5135
   at Server.Network.PacketHandlers.UnicodeSpeech(NetState state, PacketReader pvSrc) in C:\Workspaces\src\uo\aube-uo\Server\Network\PacketHandlers.cs:line 1620
   at Server.Network.MessagePump.HandleReceive(NetState ns) in C:\Workspaces\src\uo\aube-uo\Server\Network\MessagePump.cs:line 209
   at Server.Network.MessagePump.Slice() in C:\Workspaces\src\uo\aube-uo\Server\Network\MessagePump.cs:line 136
   at Server.Core.Main(String[] args) in C:\Workspaces\src\uo\aube-uo\Server\Main.cs:line 674
```

**Example Stracktrace 2**
```System.NullReferenceException: Object reference not set to an instance of an object.
   at Server.Engines.Quests.QuestHelper.EnhancedSkill(PlayerMobile player, Skill skill)
   at Server.Misc.SkillCheck.Gain(Mobile from, Skill skill)
   at Server.Misc.SkillCheck.CheckSkill(Mobile from, Skill skill, Object amObj, Double chance)
   at Server.Misc.SkillCheck.Mobile_SkillCheckDirectLocation(Mobile from, SkillName skillName, Double chance)
   at Server.Mobiles.XmlSpawnerSkillCheck.Mobile_SkillCheckDirectLocation(Mobile from, SkillName skillName, Double chance)
   at Server.Misc.RegenRates.Mobile_ManaRegenRate(Mobile from)
   at Server.Mobile.ManaTimer..ctor(Mobile m) in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 1965
   at Server.Mobile.CheckStatTimers() in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 6366
   at Server.Items.BaseJewel.OnAdded(Object parent)
   at Server.Mobile.AddItem(Item item) in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 6867
   at Server.Commands.ConvertPlayers.Convert_OnCommand(CommandEventArgs e)
   at Server.Commands.CommandSystem.Handle(Mobile from, String text, MessageType type) in C:\Workspaces\src\uo\aube-uo\Server\Commands.cs:line 258
   at Server.Mobile.DoSpeech(String text, Int32[] keywords, MessageType type, Int32 hue) in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 5135
   at Server.Network.PacketHandlers.UnicodeSpeech(NetState state, PacketReader pvSrc) in C:\Workspaces\src\uo\aube-uo\Server\Network\PacketHandlers.cs:line 1620
   at Server.Network.MessagePump.HandleReceive(NetState ns) in C:\Workspaces\src\uo\aube-uo\Server\Network\MessagePump.cs:line 209
   at Server.Network.MessagePump.Slice() in C:\Workspaces\src\uo\aube-uo\Server\Network\MessagePump.cs:line 136
   at Server.Core.Main(String[] args) in C:\Workspaces\src\uo\aube-uo\Server\Main.cs:line 674
```

**Example Stacktrace 3**
```System.NullReferenceException: Object reference not set to an instance of an object.
   at Server.BinaryFileWriter.Write(List`1 list, Boolean tidy) in C:\Workspaces\src\uo\aube-uo\Server\Serialization.cs:line 937
   at Server.Mobiles.PlayerMobile.Serialize(GenericWriter writer)
   at Server.Aube.Mobiles.AubePlayerMobile.Serialize(GenericWriter writer)
   at Server.StandardSaveStrategy.SaveMobiles(SaveMetrics metrics) in C:\Workspaces\src\uo\aube-uo\Server\Persistence\StandardSaveStrategy.cs:line 104
   at Server.DualSaveStrategy.Save(SaveMetrics metrics, Boolean permitBackgroundWrite) in C:\Workspaces\src\uo\aube-uo\Server\Persistence\DualSaveStrategy.cs:line 31
   at Server.World.Save(Boolean message, Boolean permitBackgroundWrite) in C:\Workspaces\src\uo\aube-uo\Server\World.cs:line 1160
   at Server.Commands.ConvertPlayers.Convert_OnCommand(CommandEventArgs e)
   at Server.Commands.CommandSystem.Handle(Mobile from, String text, MessageType type) in C:\Workspaces\src\uo\aube-uo\Server\Commands.cs:line 258
   at Server.Mobile.DoSpeech(String text, Int32[] keywords, MessageType type, Int32 hue) in C:\Workspaces\src\uo\aube-uo\Server\Mobile.cs:line 5135
   at Server.Network.PacketHandlers.UnicodeSpeech(NetState state, PacketReader pvSrc) in C:\Workspaces\src\uo\aube-uo\Server\Network\PacketHandlers.cs:line 1620
   at Server.Network.MessagePump.HandleReceive(NetState ns) in C:\Workspaces\src\uo\aube-uo\Server\Network\MessagePump.cs:line 209
   at Server.Network.MessagePump.Slice() in C:\Workspaces\src\uo\aube-uo\Server\Network\MessagePump.cs:line 136
   at Server.Core.Main(String[] args) in C:\Workspaces\src\uo\aube-uo\Server\Main.cs:line 674
22:27:07 Crash: Generating report...done
```

**Comment by kevin-10** [comment]
I don't this command should still be used.

**Comment by DarkLotus** [comment]
Command is flagged obsolete and was never intended to convert from PlayerMobile to your own custom class.

**Comment by Tasanar** [comment]
Yes we should just remove it.
