### ISSUE TITLE
Infinite loop after typing in path of UO

### ISSUE THREAD

**Issue by Jaen-Minetest** [ServUO/ServUO#4411]
This started happening with latest git as of May 24th. I have compiled ServUo without any errors, but when I start ServUo.exe and it asks to type in the path of UO, I type it as I always have and then it pops up a new ServUo.exe window that starts over and asks for the path of UO. This keeps looping until I close ServUO. I have a backup made from previous ServUO, tested and it works fine, so I guess I'll use it until this issue gets resolved.

**Comment by quonic** [comment]
Example of this from logs:

```
Server Crash Report
===================

ServUO Version 0.5, Build 7139.8639
Operating System: Microsoft Windows NT 6.2.9200.0
.NET Framework: 4.0.30319.42000
Time: 7/19/2019 9:48:45 AM
Mobiles: 1
Items: 1
Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Server.TileData' threw an exception. ---> System.Exception: TileData:  not found
   at Server.TileData..cctor()
   --- End of inner exception stack trace ---
   at Server.TileData.get_ItemTable()
   at Server.Item.get_ItemData()
   at Server.Item.UpdateLight()
   at Server.Items.BaseArmor..ctor(Int32 itemID)
   at Server.Mobiles.SeaMarketOfficer.InitBody()
   at Server.Mobiles.BaseVendor..ctor(String title)
   at Server.Engines.Quests.MondainQuester..ctor()
   at Server.Mobiles.SeaMarketOfficer..ctor()
   at Server.Mobiles.SeaMarketOfficer.Initialize()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Server.ScriptCompiler.Invoke(String method)
   at Server.Core.Main(String[] args)

Clients:
- Count: 0
```

**Comment by skewskewskew** [comment]
Similar issue here, different culprit.... Mine was TreasuresOfTokuno, but had the same issue from TileData. I ended up simply commenting out TreasuresOfTokuno from the project file.

Log...

```
Server Crash Report
===================

ServUO Version 0.5, Build 7214.19874
Operating System: Microsoft Windows NT 6.2.9200.0
.NET Framework: 4.0.30319.42000
Time: 10/2/2019 4:04:31 PM
Mobiles: 0
Items: 1
Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Server.TileData' threw an exception. ---> System.Exception: TileData:  not found
   at Server.TileData..cctor()
   --- End of inner exception stack trace ---
   at Server.TileData.get_ItemTable()
   at Server.Item.get_ItemData()
   at Server.Item.UpdateLight()
   at Server.Misc.TreasuresOfTokunoPersistence..ctor()
   at Server.Misc.TreasuresOfTokunoPersistence.Initialize()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Server.ScriptCompiler.Invoke(String method)
   at Server.Core.Main(String[] args)

Clients:
- Count: 0
```

**Comment by sircapted** [comment]
any fixxes? got newer publish 55 serv uo does not have this issue..

**Comment by kevin-10** [comment]
Bad Client.
