### ISSUE TITLE
Crash during save on Raspberry PI 4 / Mono

### ISSUE THREAD

**Issue by mythril** [ServUO/ServUO#4520]
I was attempting to set up ServUO on a new Raspberry Pi 4 (4gb version) to show my younger brother how to program (starting with UOSteam macros, eventually shard customization). It seemed to run fine until it came time for the thing to save, then it crashed.

So I then checked out the latest "release" 4f4b37a4c795996e37ba3706076724ddd44f9eb1 and ran make clean / deleted the `Saves` directory and tried again. Same thing, here is the trace:

```19:20:33 Core: Using dual save strategy
19:20:33 World: Saving...

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
00010000-00413000 r-xp 00000000 b3:02 38679      /usr/bin/mono-sgen
00422000-00426000 r--p 00402000 b3:02 38679      /usr/bin/mono-sgen
00426000-0042b000 rw-p 00406000 b3:02 38679      /usr/bin/mono-sgen
0042b000-00439000 rw-p 00000000 00:00 0 
01734000-02a58000 rw-p 00000000 00:00 0          [heap]
ad600000-ad700000 rw-p 00000000 00:00 0 
ad77c000-ad7fc000 rw-p 00000000 00:00 0 
ad800000-ad900000 rw-p 00000000 00:00 0 
ad97c000-ad9fc000 rw-p 00000000 00:00 0 
ada00000-adb00000 rw-p 00000000 00:00 0 
adb7c000-adbfc000 rw-p 00000000 00:00 0 
adc00000-add00000 rw-p 00000000 00:00 0 
add7c000-addfc000 rw-p 00000000 00:00 0 
ade00000-adf00000 rw-p 00000000 00:00 0 
adf7c000-adffc000 rw-p 00000000 00:00 0 
ae000000-ae100000 rw-p 00000000 00:00 0 
ae17c000-ae1fc000 rw-p 00000000 00:00 0 
ae200000-ae300000 rw-p 00000000 00:00 0 
ae31c000-ae37c000 rwxp 00000000 00:00 0 
ae37c000-ae3fc000 rw-p 00000000 00:00 0 
ae400000-ae500000 rw-p 00000000 00:00 0 
ae503000-ae553000 rwxp 00000000 00:00 0 
ae553000-ae554000 ---p 00000000 00:00 0 
ae554000-ae654000 rwxp 00000000 00:00 0 
ae654000-ae6d4000 rw-p 00000000 00:00 0 

=================================================================
	Native stacktrace:
=================================================================
	 (No frames) 


=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0xb664f430 from 0xb6fa7b00
Pkilling 0xb32ff430 from 0xb6fa7b00
Pkilling 0xb38ff430 from 0xb6fa7b00
Pkilling 0xaeeff430 from 0xb6fa7b00
Pkilling 0xae653430 from 0xb6fa7b00
Pkilling 0xb1e2a430 from 0xb6fa7b00
Entering thread summarizer pause from 0xb6fa7b00
Finished thread summarizer pause from 0xb6fa7b00.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 2944]
[New LWP 2945]
[New LWP 2965]
[New LWP 2966]
[New LWP 2967]
[New LWP 2968]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__waitpid (options=0, stat_loc=0xbeff3eb0, pid=3009) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id                                      Frame 
* 1    Thread 0xb6fa7b00 (LWP 2943) "Core Thread"     __waitpid (options=0, stat_loc=0xbeff3eb0, pid=3009) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0xb5fff430 (LWP 2944) "SGen worker"     futex_wait_cancelable (private=0, expected=0, futex_word=0x437ae8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0xb664f430 (LWP 2945) "Finalizer"       0xb6ee2088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x42fde8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0xb1e2a430 (LWP 2965) "Thread Pool Wor" __libc_read (nbytes=1024, buf=0xb3bdc990, fd=0) at ../sysdeps/unix/sysv/linux/read.c:26
  5    Thread 0xb38ff430 (LWP 2966) "Timer-Scheduler" futex_wait_cancelable (private=0, expected=0, futex_word=0x173a138) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  6    Thread 0xaeeff430 (LWP 2967) "Thread Pool I/O" __GI___poll (timeout=-1, nfds=5, fds=0xb0f348c8) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0xae653430 (LWP 2968) "Timer Thread"    futex_reltimed_wait_cancelable (private=0, reltime=0xae652248, expected=0, futex_word=0x1739cb8) at ../sysdeps/unix/sysv/linux/futex-internal.h:142

Thread 7 (Thread 0xae653430 (LWP 2968)):
#0  futex_reltimed_wait_cancelable (private=0, reltime=0xae652248, expected=0, futex_word=0x1739cb8) at ../sysdeps/unix/sysv/linux/futex-internal.h:142
#1  __pthread_cond_wait_common (abstime=0xae6522c4, mutex=0x2, cond=0x1739c90) at pthread_cond_wait.c:533
#2  __pthread_cond_timedwait (cond=0x1739c90, mutex=0x2, abstime=0xae6522c4) at pthread_cond_wait.c:667
#3  0x0032ff3c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (Thread 0xaeeff430 (LWP 2967)):
#0  __GI___poll (timeout=-1, nfds=5, fds=0xb0f348c8) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  __GI___poll (fds=0xb0f348c8, nfds=5, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:26
#2  0x00269df8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 0xb38ff430 (LWP 2966)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x173a138) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0x173a110) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x173a110, mutex=0x0) at pthread_cond_wait.c:655
#3  0x0032ff78 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0xb1e2a430 (LWP 2965)):
#0  __libc_read (nbytes=1024, buf=0xb3bdc990, fd=0) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __libc_read (fd=0, buf=0xb3bdc990, nbytes=1024) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00183e7c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0xb664f430 (LWP 2945)):
#0  0xb6ee2088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x42fde8) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x42fde8, abstime=0x0) at sem_waitcommon.c:115
#2  0xb6ee21f4 in __new_sem_wait_slow (sem=0x42fde8, abstime=0x0) at sem_waitcommon.c:282
#3  0x002b5684 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0xb5fff430 (LWP 2944)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x437ae8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0x437ac0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x437ac0, mutex=0x0) at pthread_cond_wait.c:655
#3  0x0031ed24 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0xb6fa7b00 (LWP 2943)):
#0  __waitpid (options=0, stat_loc=0xbeff3eb0, pid=3009) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=3009, stat_loc=0xbeff3eb0, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0x000b1198 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 2943) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0xae31fd44):0xae31fd34  20 00 97 e5 00 00 85 e0 06 0b 9d ed 00 0b 80 ed   ...............
0xae31fd44  00 00 a0 e3 00 00 8d e5 00 00 57 e3 06 00 00 0b  ..........W.....
0xae31fd54  20 00 97 e5 08 00 80 e2 00 00 57 e3 02 00 00 0b   .........W.....
0xae31fd64  20 00 87 e5 20 d0 8d e2 a0 81 bd e8 0e 10 a0 e1   ... ...........

=================================================================
	Managed Stacktrace:
=================================================================
	  at Server.BinaryFileWriter:Write <0x000cc>
	  at Server.Mobiles.BaseCreature:Serialize <0x0005b>
	  at Server.Mobiles.ClockworkExodus:Serialize <0x0001b>
	  at Server.StandardSaveStrategy:SaveMobiles <0x002f3>
	  at Server.DualSaveStrategy:Save <0x00183>
	  at Server.World:Save <0x0029b>
	  at Server.Misc.AutoSave:Save <0x00093>
	  at Server.Misc.AutoSave:Save <0x0000f>
	  at DelayCallTimer:OnTick <0x00043>
	  at Server.Timer:Slice <0x00107>
	  at Server.Core:Main <0x01453>
	  at <Module>:runtime_invoke_void_object <0x000e7>
=================================================================
Aborted
make: *** [Makefile:19: run] Error 134
```

Some extra info:
```
$ mono --version
Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:57:00 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
```
```
$ mcs --version
Mono C# compiler version 6.4.0.198
```
```
$ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

I am a programmer (but not specifically a .NET guy) so I can delve in a bit, any ideas what I should poke at?

**Comment by mythril** [comment]
I manually applied this patch: https://github.com/ServUO/ServUO/pull/1565/commits/159f88514bf645abe90db6cfe6b0931c422918a8 and it worked.

**Comment by kevin-10** [comment]
Can you reference this in the forums please?
