### ISSUE TITLE
crash restart

### ISSUE THREAD

**Issue by sircapted** [ServUO/ServUO#4524]
--- End of inner exception stack trace ---
   at Server.TileData.get_ItemTable()
   at Server.Item.get_ItemData() in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Server\Item.cs:line 5862
   at Server.Item.UpdateLight() in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Server\Item.cs:line 6230
   at Server.Item..ctor(Int32 itemID) in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Server\Item.cs:line 6211
   at Server.Items.BaseArmor..ctor(Int32 itemID) in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Scripts\Items\Equipment\Armor\BaseArmor.cs:line 2362
   at Server.Items.ChainChest..ctor() in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Scripts\Items\Equipment\Armor\ChainChest.cs:line 23
   at Server.Mobiles.SeaMarketOfficer.InitBody() in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Scripts\Services\Expansions\High Seas\Quests\ProfessionalBountyQuest\Mobiles\SeaMarketOfficer.cs:line 32
   at Server.Mobiles.BaseVendor..ctor(String title) in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Scripts\Mobiles\NPCs\BaseVendor.cs:line 319
   at Server.Engines.Quests.MondainQuester..ctor() in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Scripts\Services\MondainsLegacyQuests\MondainQuester.cs:line 12
   at Server.Mobiles.SeaMarketOfficer..ctor() in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Scripts\Services\Expansions\High Seas\Quests\ProfessionalBountyQuest\Mobiles\SeaMarketOfficer.cs:line 14
   at Server.Mobiles.SeaMarketOfficer.Initialize() in C:\Users\ghost nobody\Desktop\servuo server\ServUO-master\Scripts\Services\Expansions\High Seas\Quests\ProfessionalBountyQuest\Mobiles\SeaMarketOfficer.cs:line 143
   --- End of inner exception stack trace ---

help

**Comment by sircapted** [comment]
trying to find a newer client mb its just a missing mul or uop file....

**Comment by kevin-10** [comment]
Bad client.
