### ISSUE TITLE
Server crash at startup (#4550)

### ISSUE THREAD

**Issue by LordFenris** [ServUO/ServUO#4551]
Crash recorded today after implementing patches from package # 4550 - during server startup

Server Crash Report
===================

ServUO Version 0.5, Build 7354.24719
Operating System: Microsoft Windows NT 6.2.9200.0
.NET Framework: 4.0.30319.42000
Time: 19.02.2020 12:49:12
Mobiles: 60208
Items: 411995
Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
at Server.Multis.BaseGalleon.CheckAddon(Item item)
at Server.Multis.BaseBoat.CanFit(Point3D p, Map map, Int32 itemID)
at Server.Multis.BaseBoat.Move(Direction dir, Int32 speed, Int32 clientSpeed, Boolean message)
at Server.Multis.BaseBoat.DoMovement(Boolean message, Boolean single)
at Server.Multis.BaseBoat.MoveTimer.OnTick()
at Server.Timer.Slice()
at Server.Core.Main(String[] args)

**Comment by kevin-10** [comment]
Fix coming shortly.
