### ISSUE TITLE
Latest github 4552 loyality crash

### ISSUE THREAD

**Issue by LordFenris** [ServUO/ServUO#4553]
Crash occurs each time you click on the loyality ranking options in the character menu

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Server.Engines.Points.LoyaltyRatingGump..ctor(PlayerMobile pm)
   at Server.Engines.Points.LoyaltyRating.OnClick()
   at Server.Network.PacketHandlers.ContextMenuResponse(NetState state, PacketReader pvSrc)
   at Server.Network.MessagePump.HandleReceive(NetState ns)
   at Server.Network.MessagePump.Slice()
   at Server.Core.Main(String[] args)

**Comment by LordFenris** [comment]
By the way - we noticed that over time the number of NPCs from which you can buy etherela sand in Minoc increases - as if more spawns were generated - despite the existing ones.
