### ISSUE TITLE
Specific Crash

### ISSUE THREAD

**Issue by DragnMaw** [ServUO/ServUO#4932]
Been getting a crash on our Server, using the ServUO Pub58-WIP, when the Barrels during the Undersea Encounter are destroyed from Hit Area Damage.

Items: 222349
Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Server.Map.MobileEnumerator.MoveNext() in R:\AUUO\Server\Map.cs:line 2614
   at System.Linq.Enumerable.<OfTypeIterator>d__95`1.MoveNext()
   at Server.Mobiles.AreaEffect.<FindValidTargets>d__19.MoveNext() in R:\AUUO\Scripts\Services\Pet Training\AreaEffects.cs:line 105
   at System.Linq.Enumerable.<OfTypeIterator>d__95`1.MoveNext()
   at Server.Mobiles.LifeDrain.DoEffects(BaseCreature creature, Mobile defender, Int32& damage) in R:\AUUO\Scripts\Services\Pet Training\SpecialAbility.cs:line 2189
   at Server.Mobiles.SpecialAbility.Trigger(BaseCreature creature, Mobile defender, Int32& damage) in R:\AUUO\Scripts\Services\Pet Training\SpecialAbility.cs:line 171
   at Server.Mobiles.SpecialAbility.CheckCombatTrigger(Mobile attacker, Mobile defender, Int32& damage, DamageType type) in R:\AUUO\Scripts\Services\Pet Training\SpecialAbility.cs:line 79
   at Server.AOS.Damage(IDamageable damageable, Mobile from, Int32 damage, Boolean ignoreArmor, Int32 phys, Int32 fire, Int32 cold, Int32 pois, Int32 nrgy, Int32 chaos, Int32 direct, Boolean keepAlive, DamageType type) in R:\AUUO\Scripts\Misc\AOS.cs:line 291
   at Server.Items.BaseWeapon.OnHit(Mobile attacker, IDamageable damageable, Double damageBonus) in R:\AUUO\Scripts\Items\Equipment\Weapons\BaseWeapon.cs:line 2181
   at Server.Items.BaseWeapon.OnSwing(Mobile attacker, IDamageable damageable, Double damageBonus) in R:\AUUO\Scripts\Items\Equipment\Weapons\BaseWeapon.cs:line 1295
   at Server.Items.BaseWeapon.OnSwing(Mobile attacker, IDamageable damageable) in R:\AUUO\Scripts\Items\Equipment\Weapons\BaseWeapon.cs:line 1253
   at Server.Mobile.CombatTimerOnTick() in R:\AUUO\Server\Mobile.cs:line 1954
   at Server.Mobile.<>c.<StartCombatTimer>b__401_0(Mobile m) in R:\AUUO\Server\Mobile.cs:line 1920
   at Server.RegistryTimer`1.OnTick() in R:\AUUO\Server\TimerRegistry.cs:line 301
   at Server.Timer.Slice() in R:\AUUO\Server\Timer.cs:line 419
   at Server.Core.Run() in R:\AUUO\Server\Main.cs:line 678

**Comment by Vorspire** [comment]
That code (and the bug) isn't active unless you specifically disabled [this check](https://github.com/ServUO/ServUO/blob/b3edab8584fed32283a859a147a18d0e330e1795/Server/Map.cs#L43)
